version: "3.8"
services:
  web:
    container_name: revtracker
    build:
      context: ./app
      dockerfile: Dockerfile
    image: revtracker:latest
    command: flask run --host=0.0.0.0 --port=5000
    volumes:
      - ./app/:/app/
    ports:
      - 5000:5000
    environment:
      - FLASK_APP=wsgi.py
      - FLASK_ENV=development
      - DB_NAME=revtracker_flask
      - DB_USER=postgres
      - DB_PASSWORD=admin123
      - DB_HOST=pg
      - DB_PORT=5432
      - DATABASE=postgres
      - DATABASE_URL=postgresql://postgres:admin123@pg:5432/revtracker_flask
    depends_on:
      - pg
  pg:
    container_name: postgres
    image: postgres:13.2-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: revtracker_flask
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:5.2
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_LISTEN_PORT: 5433
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    ports:
      - "5433:5433"
    depends_on:
      - pg
volumes:
  pg_data: